import Head from 'next/head'
import MiddleBadge from '../Components/MainPage/MiddleBadge';
import SlickSlider from '../Components/MainPage/Slider';
export default function Home() {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SlickSlider />
      <MiddleBadge/>
    </div>
  )
}
